server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio_service?useTimeZone=true&serverTimeZone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySql5InooDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: cambio_service
    usuario: root
    password: password